<%@ Page Title="" Language="C#" MasterPageFile="~/Rector.Master" AutoEventWireup="true" CodeBehind="DisplayRector.aspx.cs" Inherits="final.DisplayRector" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Panel ID="Panel1" runat="server">
    <br/>
    <br/>
    <br/>
    <br/>
    <asp:GridView ID="GridView1" runat="server" HorizontalAlign="Center" Width="95%" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            AutoGenerateSelectButton="True" BackColor="White" BorderColor="#999999" 
            BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" 
            GridLines="Vertical" 
             >
        <AlternatingRowStyle BackColor="#C5E0B3" />
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="#70AD47" Font-Bold="True" ForeColor="#FFFFFF" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#FF9999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#808080" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
    </asp:Panel>
</asp:Content>
