<%@ Page Title="" Language="C#" MasterPageFile="~/Student.Master" AutoEventWireup="true" CodeBehind="DisplayStudent.aspx.cs" Inherits="final.DisplayStudent" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Panel ID="Panel1" runat="server">
    <br/>
    <br/>
    <br/>
    <br/>
    <asp:GridView ID="GridView1" runat="server" HorizontalAlign="Center" Width="95%" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            AutoGenerateSelectButton="True" BackColor="White" BorderColor="#999999" 
            BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" 
            GridLines="Vertical">
        <AlternatingRowStyle BackColor="#C5E0B3" />
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="#70AD47" Font-Bold="True" ForeColor="#FFFFFF" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#FF9999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#808080" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
    </asp:Panel>
    <asp:Panel ID="Panel2" runat="server" >
        <br/>
        <br/>
        <br/>        
        <asp:PlaceHolder ID="PlaceHolder1" runat="server"></asp:PlaceHolder>
    </asp:Panel>
    <asp:Panel ID="Panel3" runat="server">
    <section id="two" class="wrapper style2">
    <div class="inner" style="width: 60%;">
        <div class="box" align="center" >
            <div class="content">
            <form>
                <table>
                    <tr style="background-color: #FFFFFF">
                        <td colspan="2">
                            <h2>Personal Details</h2>
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>First Name:</td>
                        <td>
                            <asp:TextBox ID="txtFName" runat="server"></asp:TextBox>
 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
ControlToValidate="txtFName" ErrorMessage="Please Enter Your First Name" ForeColor="Red"></asp:RequiredFieldValidator>
<asp:RegularExpressionValidator ID="RegularExpressionValidator" runat="server" 
ControlToValidate="txtFName" ErrorMessage="Only String Allow" ForeColor="Red" 
 ValidationExpression="[A-za-z]*$"></asp:RegularExpressionValidator>
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>Middel Name:</td>
                        <td>
                            <asp:TextBox ID="txtMName" runat="server"></asp:TextBox>
 <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" 
ControlToValidate="txtMName" ErrorMessage="Please Enter Your Middel Name" ForeColor="Red"></asp:RequiredFieldValidator>
<asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
ControlToValidate="txtMName" ErrorMessage="Only String Allow" ForeColor="Red" 
 ValidationExpression="[A-za-z]*$"></asp:RegularExpressionValidator>
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>Last Name:</td>
                        <td>
                            <asp:TextBox ID="txtLName" runat="server"></asp:TextBox>
 <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
ControlToValidate="txtLName" ErrorMessage="Please Enter Your Last Name" ForeColor="Red"></asp:RequiredFieldValidator>
<asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" 
ControlToValidate="txtLName" ErrorMessage="Only String Allow" ForeColor="Red" 
 ValidationExpression="[A-za-z]*$"></asp:RegularExpressionValidator>
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>Gender:</td>
                        <td>
                            <asp:RadioButtonList ID="rblGender" runat="server" RepeatDirection="Horizontal">
                                <asp:ListItem Text="Male" Value="Male" Selected="True" ></asp:ListItem>
                                <asp:ListItem Text="Female" Value="Female"></asp:ListItem>
                            </asp:RadioButtonList>
                        </td>
                    </tr>
              
                    <tr style="background-color: #FFFFFF" >
                        <td colspan="2">
                            Parent's Details
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF" >
                        <td>Mother Name:</td>
                        <td><asp:TextBox ID="txtMotherName" runat="server"></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" 
                ControlToValidate="txtMotherName" ErrorMessage="Please Enter Your Mother Name" ForeColor="Red"></asp:RequiredFieldValidator>
<asp:RegularExpressionValidator ID="RegularExpressionValidator8" runat="server" 
                ControlToValidate="txtMotherName" ErrorMessage="Only String Allow" ForeColor="Red" 
                ValidationExpression="[A-za-z]*$"></asp:RegularExpressionValidator>
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF" >
                        <td>Father Name:</td>
                        <td><asp:TextBox ID="txtFatherName" runat="server"></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" 
                ControlToValidate="txtFatherName" ErrorMessage="Please Enter Your Father Name" ForeColor="Red"></asp:RequiredFieldValidator>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator6" runat="server" 
                ControlToValidate="txtFatherName" ErrorMessage="Only String Allow" ForeColor="Red" 
                ValidationExpression="[A-za-z]*$"></asp:RegularExpressionValidator>                      
                        </td>
                    </tr>
                
                    <tr style="background-color: #FFFFFF" >
                        <td colspan="2">
                            Address Details
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF" >
                        <td>Address:</td>
                        <td><asp:TextBox ID="txtAddress" runat="server" TextMode="MultiLine"></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" 
                ControlToValidate="txtAddress" ErrorMessage="Please Enter Your Address" ForeColor="Red"></asp:RequiredFieldValidator>                        
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF" >
                        <td>City:</td>
                        <td><asp:TextBox ID="txtCity" runat="server"></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator8" runat="server" 
                ControlToValidate="txtCity" ErrorMessage="Please Enter Your City" ForeColor="Red"></asp:RequiredFieldValidator>    
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>PIN Code:</td>
                        <td><asp:TextBox ID="txtPINCode" runat="server" TextMode="Number"></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator9" runat="server" 
                ControlToValidate="txtPINCode" ErrorMessage="Please Enter PIN Code" ForeColor="Red"></asp:RequiredFieldValidator>
 
                        </td>
                    </tr>
                
                    <tr style="background-color: #FFFFFF">
                        <td colspan="2">
                            Contact Details
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>EmailID:</td>
                        <td><asp:TextBox ID="txtEmailID" runat="server" TextMode="Email"></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator10" runat="server" 
                ControlToValidate="txtPINCode" ErrorMessage="Please Enter EmailId" ForeColor="Red"></asp:RequiredFieldValidator>                        
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>Student Contact No:</td>
                        <td><asp:TextBox ID="txtContactNo" runat="server" ></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator11" runat="server" 
                ControlToValidate="txtPINCode" ErrorMessage="Please Enter Student Contact No" ForeColor="Red"></asp:RequiredFieldValidator>                        
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>Parents Contact No:</td>
                        <td><asp:TextBox ID="txtParentsContactNo" runat="server" ></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator12" runat="server" 
                ControlToValidate="txtPINCode" ErrorMessage="Please Enter Parents Contact No" ForeColor="Red"></asp:RequiredFieldValidator>                        
                        </td>
                    </tr>
                
                    <tr style="background-color: #FFFFFF">
                        <td colspan="2">
                            Education Details
                        </td>
                    </tr>
                    <tr style="background-color: #FFFFFF">
                        <td>Department:</td>
                        <td><asp:TextBox ID="txtDepartment" runat="server"></asp:TextBox>
<asp:RequiredFieldValidator ID="RequiredFieldValidator13" runat="server" 
                ControlToValidate="txtPINCode" ErrorMessage="Please Enter Department" ForeColor="Red"></asp:RequiredFieldValidator>
                <asp:Button ID="btnUpdate" runat="server" Text="Update" CssClass="button0 button2" 
                                onclick="btnUpdate_Click"></asp:Button>
                            <asp:Label ID="lblErrorMsg" runat="server" Text=""></asp:Label>
                        </td>
                    </tr>
                </table>
            </form>
            </div>
        </div>
    </div>
    </section>
    </asp:Panel>
</asp:Content>
